global:
  image: "hashicorp/consul:1.13.2"
  datacenter: "dc1"
  name: consul
  tls:
    grpc:
      use_auto_cert: true
    enabled: true
server:
  replicas: 1
connectInject:
  replicas: 1
  enabled: true
controller:
  enabled: true
ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer
    port:
      http: 8500
apiGateway:
  enabled: true
  image: hashicorp/consul-api-gateway:0.4.0
  managedGatewayClass:
    serviceType: LoadBalancer
    useHostPorts: true